---

- name: Add repository "docker-ce"
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    owner: root
    mode: 0644
    force: yes
...
