all:
  children:
    hosts:
      hosts:
        x86_64:
    dockers:
      children:
        x86_64-dockers:
    x86_64:
      hosts:
        x86_64:
          ansible_host: "<IP/domain/ssh alias>"
          ansible_user: "<a host user>"
      children:
        x86_64-dockers:
          hosts:
            x86_64-al8:
              ansible_host: "<IP/domain/ssh alias>"  # the same as a host machine
              ansible_user: "root"
              ansible_port: "{{ sshd_ports_in_containers[8] }}"
            x86_64-al9:
              ansible_host: "<IP/domain/ssh alias>"  # the same as a host machine
              ansible_user: "root"
              ansible_port: "{{ sshd_ports_in_containers[9] }}"
