all:
  children:
    hosts:
      hosts:
        s390x:
    dockers:
      children:
        s390x-dockers:
    s390x:
      hosts:
        s390x:
          ansible_host: "<IP/domain/ssh alias>"
          ansible_user: "<a host user>"
      children:
        s390x-dockers:
          hosts:
            s390x-al8:
              ansible_host: "<IP/domain/ssh alias>"  # the same as a host machine
              ansible_user: "root"
              ansible_port: "{{ sshd_ports_in_containers[8] }}"
            s390x-al9:
              ansible_host: "<IP/domain/ssh alias>"  # the same as a host machine
              ansible_user: "root"
              ansible_port: "{{ sshd_ports_in_containers[9] }}"
